/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_potoman_Plop */

#ifndef _Included_com_potoman_Plop
#define _Included_com_potoman_Plop
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_potoman_Plop
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_potoman_Plop_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_potoman_Plop
 * Method:    timesHello
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_potoman_Plop_timesHello
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT jboolean JNICALL Java_com_potoman_Plop_initCanvas
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif


